exp_name: COMET_2p_try
net:  COMET_net #rationale_net
dataset: Imagenet9 # NICO  Imagenet9 Cifar
class_num: 9  #9 
player_num: 2
pretrained: False
image_folder: /data2/wangtan/causal-invariant-attention/dataset/NICO/multi_classification
cxt_dic_path: /home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2context.json
class_dic_path: /home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2label.json # /home/xzz5508/code/Imbalance_ood/Imagenet_9name2label.json #/home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2label.json
training_opt:
  m_ploss: 1  # fix it as one
  m_closs: 4 # default 1
  m_m1: 100 # default 100
  mask_th: 0.6 # default 0.2
  gap_th: 2 # default 1

  seed: 0 # default 0
  batch_size: 128 
  optim:
    sched: baseline
  lr: 0.0005 # 0.0005
  warm: 2
  epoch: 200
  milestones: [80, 120, 160]
  # milestones: [80, 140, 200]
  save_epoch: 20
  print_batch: 1
  mean:  [0.4717, 0.4499, 0.3837] # nico: [0.52418953, 0.5233741, 0.44896784] imagenet9: [0.4717, 0.4499, 0.3837]
  std:   [0.2600, 0.2516, 0.2575]   # nico:  [0.21851876, 0.2175944, 0.22552039] imagenet9: [0.2600, 0.2516, 0.2575] 
variance_opt:
  balance_factor: 1
  #training_dist: {'dog': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'cat': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'bear': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'bird': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'cow': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'elephant': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'horse': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'monkey': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'rat': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass'],
  #                'sheep': ['rock', 'dim', 'water', 'autumn', 'outdoor', 'grass']}
  mode: 'baseline'
  env_type: 'baseline'
resume: False
