exp_name: nico_resvit18_multi_unshuffle_bf0.02_lr0.01
net: resnet18_ours_cbam_multi
dataset: NICO
image_folder: /data2/wangtan/causal-invariant-attention/dataset/NICO/multi_classification
cxt_dic_path: /home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2label.json
class_dic_path: /home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2label.json
training_opt:
  seed: 0
  classes: 60
  batch_size: 32
  lr: 0.05
  warm: 2
  epoch: 200
  milestones: [80, 120, 160]
  # milestones: [80, 140, 200]
  save_epoch: 20
  print_batch: 1
  mean: [0.52418953, 0.5233741, 0.44896784]
  std: [0.21851876, 0.2175944, 0.22552039]
variance_opt:
  balance_factor: 1
  env: False
  mode: 'ours'
  erm_flag: True
  sp_flag: False
  n_env: 1
  env_type: 'auto-iter'
  split_renew: 40
  split_renew_iters: 20
  from_scratch: False
  ref_model_path: /home/xzz5508/code/Imbalance_ood/CaaM_original_test/CaaM/0-NICO/checkpoint/Used_for_Caam_refer/resnet18/check_used_resnet18/resnet18-180-regular.pth
  penalty_weight: 5e5
  penalty_anneal_iters: 0
  #2 blocks, 4 layers
  split_layer: 2
resume: False