class_dic_path: /home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2label.json
class_num: 9
cxt_dic_path: /home/xzz5508/code/Imbalance_ood/NICO_dataset/NICO_plus/name2context.json
dataset: Imagenet9
exp_name: COMET_2p_try
image_folder: /data2/wangtan/causal-invariant-attention/dataset/NICO/multi_classification
net: COMET_net
player_num: 2
pretrained: false
resume: false
training_opt:
  batch_size: 128
  epoch: 200
  gap_th: 2
  lr: 0.0005
  m_closs: 4
  m_m1: 100
  m_ploss: 1
  mask_th: 0.6
  mean:
  - 0.4717
  - 0.4499
  - 0.3837
  milestones:
  - 80
  - 120
  - 160
  optim:
    sched: baseline
  print_batch: 1
  save_epoch: 20
  seed: 0
  std:
  - 0.26
  - 0.2516
  - 0.2575
  warm: 2
variance_opt:
  balance_factor: 1
  env_type: baseline
  mode: baseline
